version: "3.8"
services:
  worker-service-1:
    env_file:
      - ./configs/.env.${GUARDIAN_ENV}.guardian.system
    build:
      context: .
      dockerfile: ./worker-service/Dockerfile
    environment:
      - GUARDIAN_ENV=${GUARDIAN_ENV}
      - SERVICE_CHANNEL:"worker.1"
    expose:
      - 6555
    volumes:
      - ./worker-service/tls:/usr/local/worker-service/tls:ro
      - ./worker-service/configs:/usr/local/worker-service/configs:ro

volumes:
  mongo:
  prometheus_data: {}
  grafana_data: {}
  branding_data:
  # volume-guardian-service:
  # volume-ui-service:
  # volume-mrv-sender:
  #  volume-message-broker:

networks:
  monitoring:
    driver: bridge
