name: Guardian CI API Tests
on:
  workflow_dispatch:
    description: 'Manual run'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
        mongodb-version: [ 7.0.5 ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: |
          pushd interfaces
          yarn run build
          popd
          pushd common
          yarn run build
          popd
          pushd notification-service
          yarn run build
          popd
          pushd logger-service
          yarn run build
          popd
          pushd auth-service
          yarn run build
          popd
          pushd guardian-service
          yarn run build
          popd
          pushd policy-service
          yarn run build
          popd
          pushd worker-service
          yarn run build
          popd
          pushd api-gateway
          yarn run build
          popd
      - name: Start NatsMQ
        uses: onichandame/nats-action@master
        with:
          port: "4222"
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run Guardian
        run: |
          pushd notification-service
          npm start &
          sleep 20
          popd
          pushd logger-service
          npm start &
          sleep 20
          popd
          pushd auth-service
          npm start &
          sleep 20
          popd
          pushd guardian-service
          npm start &
          sleep 20
          popd
          pushd policy-service
          npm start &
          sleep 20
          popd
          pushd worker-service
          npm start &
          sleep 20
          popd
          pushd api-gateway
          npm start &
          sleep 20
          popd
          sleep 60
        env:
          CI: true
          OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
          OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}
          IPFS_STORAGE_KEY: ${{ secrets.IPFS_STORAGE_KEY }}
          IPFS_STORAGE_PROOF: ${{ secrets.IPFS_STORAGE_PROOF }}

      - name: Run tests with Cypress
        run: |
          pushd e2e-tests
          npm install
          npx cypress run --spec cypress/e2e/api-tests/**/*.cy.js            
          popd
      - name: Publish API Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test_results/**/*.xml
