name: Guardian CI API Tests
on:
  workflow_dispatch:
    description: 'Manual run'
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0.3
        ports:
          - 27017:27017/tcp

      natsmq:
        image: nats:2.9.8
        ports:
          - 4222:4222/tcp

    strategy:
      matrix:
        node-version: [ 16.x ]
        mongodb-version: [ 4.4 ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn
          pushd interfaces
          yarn run build
          popd
          pushd common
          yarn run build
          popd
          pushd notification-service
          yarn run build
          popd
          pushd logger-service
          yarn run build
          popd
          pushd auth-service
          yarn run build
          popd
          pushd guardian-service
          yarn run build
          popd
          pushd policy-service
          yarn run build
          popd
          pushd worker-service
          yarn run build
          popd
          pushd api-gateway
          yarn run build
          popd
        env:
          CI: true
      - name: Run tests
        run: |
          pushd api-tests
          npm install
          npm run test:ci
          popd
        env:
          CI: true
          OPERATOR_ID: ${{ secrets.OPERATOR_ID }}
          OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}
          IPFS_STORAGE_API_KEY: ${{ secrets.IPFS_STORAGE_API_KEY }}
          HASHICORP_HOST: localhost
          HASHICORP_PORT: ${{ job.services.hashicorpvault.ports[8200] }}
      - name: Publish API Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test_results/**/*.xml
